Fixed stacking error:
RuntimeError: stack expects each tensor to be equal size, but got [19] at entry 0 and [18] at entry 1

 Traceback (most recent call last):
1
File "./miners/gpt2_genesis.py" line 223 in run [args] [locals]
	run arguments:
self 	<class '__main__.Miner'>
	run local variables:
self 	<class '__main__.Miner'>
self.train()
2
File "./miners/gpt2_genesis.py" line 373 in train [args] [locals]
	train arguments:
self 	<class '__main__.Miner'>
	train local variables:
run_epoch 	<class 'function'>
self 	<class '__main__.Miner'>
run_epoch()
3
File "./miners/gpt2_genesis.py" line 317 in run_epoch [locals]
	run_epoch local variables:
batch 	<class 'torch.Tensor'>
batch_weights 	<class 'torch.Tensor'>
dataloader 	<class 'torch.utils.data.dataloader.DataLoader'>
dlosses 	[0.21415889263153076, 0.5692493915557861, 0.5679144859313965, 0.2216050922870636, 0.1881854236125946, 0.21778111159801483, 0.30200833082199097, 0.5621492266654968, 0.5629610419273376, 0.39807748794555664, ...]
index 	845
it 	38
llosses 	[7.508652687072754, 7.099236965179443, 6.37581729888916, 6.8982014656066895, 6.961132049560547, 6.5989460945129395, 6.702086925506592, 6.8151750564575195, 7.1100053787231445, 6.5846333503723145, ...]
loss 	<class 'torch.Tensor'>
losses 	[15.60052490234375, 18.51651382446289, 17.794904708862305, 14.51870346069336, 14.72296142578125, 14.7494535446167, 14.709714889526367, 18.234722137451172, 18.52910614013672, 15.123245239257812, ...]
output 	<class 'types.SimpleNamespace'>
pbar 	<class 'qqdm.core.qqdm'>
rlosses 	[7.877713680267334, 10.848028182983398, 10.85117244720459, 7.39889669418335, 7.573644638061523, 7.9327263832092285, 7.7056193351745605, 10.85739803314209, 10.85614013671875, 8.140534400939941, ...]
self 	<class '__main__.Miner'>
for it, (batch) in pbar:
4
File "/usr/local/lib/python3.8/dist-packages/qqdm/core.py" line 89 in __iter__ [args] [locals]
	__iter__ arguments:
self 	<class 'qqdm.core.qqdm'>
	__iter__ local variables:
iterable 	<class 'enumerate'>
last_print_n 	39
n 	39
obj 	[ 38, "<class 'torch.Tensor'>" ]
self 	<class 'qqdm.core.qqdm'>
for obj in iterable:
5
File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py" line 517 in __next__ [args] [locals]
	__next__ arguments:
self 	<class 'torch.utils.data.dataloader._SingleProcessDataLoaderIter'>
	__next__ local variables:
self 	<class 'torch.utils.data.dataloader._SingleProcessDataLoaderIter'>
data = self._next_data()
6
File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py" line 557 in _next_data [args] [locals]
	_next_data arguments:
self 	<class 'torch.utils.data.dataloader._SingleProcessDataLoaderIter'>
	_next_data local variables:
index 	[ 78, 79 ]
self 	<class 'torch.utils.data.dataloader._SingleProcessDataLoaderIter'>
data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
7
File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py" line 47 in fetch [args] [locals]
	fetch arguments:
self 	<class 'torch.utils.data._utils.fetch._MapDatasetFetcher'>
possibly_batched_index 	[ 78, 79 ]
	fetch local variables:
data 	[ "<class 'torch.Tensor'>", "<class 'torch.Tensor'>" ]
possibly_batched_index 	[ 78, 79 ]
self 	<class 'torch.utils.data._utils.fetch._MapDatasetFetcher'>
return self.collate_fn(data)
8
File "/opt/bittensor/bittensor/dataloaders/text_dataloader.py" line 200 in collate_fn [args] [locals]
	collate_fn arguments:
self 	<class 'bittensor.dataloaders.text_dataloader.GenesisTextDataloader'>
batch 	[ "<class 'torch.Tensor'>", "<class 'torch.Tensor'>" ]
	collate_fn local variables:
batch 	[ "<class 'torch.Tensor'>", "<class 'torch.Tensor'>" ]
self 	<class 'bittensor.dataloaders.text_dataloader.GenesisTextDataloader'>
return torch.utils.data.dataloader.default_collate(batch)
9
File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/collate.py" line 55 in default_collate [args] [locals]
	default_collate arguments:
batch 	[ "<class 'torch.Tensor'>", "<class 'torch.Tensor'>" ]
	default_collate local variables:
batch 	[ "<class 'torch.Tensor'>", "<class 'torch.Tensor'>" ]
elem 	<class 'torch.Tensor'>
elem_type 	<class 'type'>
out 	None
return torch.stack(batch, 0, out=out)